# ~/.tmuxinator/peterdohertys-website.yml

name: peterdohertys-website
root: ~/projects/peterdohertys-website
windows:
  - work:
      layout: main-vertical
      panes:
        - stack clean && stack build && stack exec site clean && stack exec site watch
        -
